variable "project-name" {}
variable "x86-cluster-host" {}
variable "z-cluster-host" {}
variable "power-cluster-host" {}
variable "image-namespace" {}
variable "image-server" {}
variable "gitops-repo" {}
variable "github-user" {}
variable "github-token" {}
variable "smee-client" {}
variable "frontendservice" {}
variable "productcatalogservice" {}
variable "cartservice" {}
variable "shippingservice" {}
variable "checkoutservice" {}
variable "recommendationservice" {}
variable "paymentservice" {}
variable "emailservice" {}
variable "currencyservice" {}

